services:
  mysql:
    container_name: mysql
    image: mysql:8.4
#    env_file:
#      - .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - onlineshop-network

networks:
  onlineshop-network:
    driver: bridge

volumes:
  mysql: