services:
  mysql:
    container_name: mysql
    image: mysql:8.4
#    env_file:
#      - .env
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - onlineshop-network
  redis:
    container_name: redis
    image: redis:7.4
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - onlineshop-network
    volumes:
      - redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    restart: unless-stopped
  maildev:
    image: maildev/maildev:2.1.0
    container_name: maildev_container
    ports:
      - "1025:1025"
      - "1080:1080"

networks:
  onlineshop-network:
    driver: bridge

volumes:
  mysql:
  redis: