spring:

#  # uncomment this code if you are using .env file to define environment variables
#  config:
#    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/online_shop
    username: xdpsx
    password: xdpsxpass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

cloudinary:
  api:
    key: ${CLOUDINARY_API_KEY}
    secret: ${CLOUDINARY_API_SECRET}
  cloud:
    name: ${CLOUDINARY_CLOUD_NAME}

app:
  jwt:
    secret: AxdbTQmW/abSjS3TpqhS2rHHUTtK8ESb0xq9uueSj34=
    expiration:
      seconds: 3600
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001
  oauth2:
      redirect-uri: http://localhost:3001/oauth2/redirect
      error-uri: http://localhost:3001/login

payment:
  vnpay:
    tmn-code: ${VNPAY_TMN_CODE}
    secret-key: ${VNPAY_SECRET_KEY}
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:3001/payments/%s/redirect
    timeout: 15 # in minutes