server:
  port: 8080
#  compression: # Using GZIP to compress API data
#    enabled: true
#    mime-types: application/json

spring:
  application:
    name: onlineshop
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

