spring:

#  # uncomment this code if you are using .env file to define environment variables
#  config:
#    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/online_shop
    username: xdpsx
    password: xdpsxpass
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cloudinary:
  api:
    key: ${CLOUDINARY_API_KEY}
    secret: ${CLOUDINARY_API_SECRET}
  cloud:
    name: ${CLOUDINARY_CLOUD_NAME}